deepspeed --include localhost:1 fastchat/train/train_baichuan.py \
    --model_name_or_path ../models/Baichuan2-13B-Chat \
    --data_path retrain_train.json \
    --output_dir ./checkpoints \
    --num_train_epochs 10 \
    --fp16 True \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "steps" \
    --eval_steps 100  \
    --save_strategy "steps" \
    --save_steps 100 \
    --save_total_limit 512 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_strategy "steps" \
    --logging_steps 128 \
    --tf32 True \
    --model_max_length 1024 \
    --deepspeed playground/deepspeed_config.json \
    --gradient_checkpointing False
